name: Migrate PROD Prisma database
on:
  workflow_dispatch: # Manual trigger button

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production # Required for env secrets
    steps:
      - name: Debug secret
        run: |
          echo "DB_URL length: ${#DATABASE_URL}"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
